//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azw.FacialOsc.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azw.FacialOsc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   2.0.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonConfig {
            get {
                return ResourceManager.GetString("ButtonConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye Tracking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonEyeTracking {
            get {
                return ResourceManager.GetString("ButtonEyeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Facial Tracking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonFaceTracking {
            get {
                return ResourceManager.GetString("ButtonFaceTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonResetAll {
            get {
                return ResourceManager.GetString("ButtonResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRevert {
            get {
                return ResourceManager.GetString("ButtonRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigButtonSave {
            get {
                return ResourceManager.GetString("ConfigButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save (*) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigButtonSaveDirty {
            get {
                return ResourceManager.GetString("ConfigButtonSaveDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigEyeTracker {
            get {
                return ResourceManager.GetString("ConfigEyeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye tracker target FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigEyeTrackerTargetFps {
            get {
                return ResourceManager.GetString("ConfigEyeTrackerTargetFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLanguage {
            get {
                return ResourceManager.GetString("ConfigLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lip tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLipTracker {
            get {
                return ResourceManager.GetString("ConfigLipTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faciel tracker target FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLipTrackerTargetFps {
            get {
                return ResourceManager.GetString("ConfigLipTrackerTargetFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max gaze angle (degree) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigMaxGazeAngle {
            get {
                return ResourceManager.GetString("ConfigMaxGazeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigSelectAll {
            get {
                return ResourceManager.GetString("ConfigSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigTheme {
            get {
                return ResourceManager.GetString("ConfigTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset all configurations to the default value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogResetAllMessage {
            get {
                return ResourceManager.GetString("DialogResetAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo all changes to the startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogRevertMessage {
            get {
                return ResourceManager.GetString("DialogRevertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelApplicationFps {
            get {
                return ResourceManager.GetString("LabelApplicationFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDeviceFps {
            get {
                return ResourceManager.GetString("LabelDeviceFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target FPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelTargetFps {
            get {
                return ResourceManager.GetString("LabelTargetFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Vive Pro Eye need to be calibrated. The device might not able to use until calibration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCalibrationRequired {
            get {
                return ResourceManager.GetString("MessageCalibrationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCurrentVersion {
            get {
                return ResourceManager.GetString("MessageCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured when starting the device:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDeviceError {
            get {
                return ResourceManager.GetString("MessageDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another version is published: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDifferentVersionExists {
            get {
                return ResourceManager.GetString("MessageDifferentVersionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The detail of error: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageErrorDetail {
            get {
                return ResourceManager.GetString("MessageErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageLatestVersion {
            get {
                return ResourceManager.GetString("MessageLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration cannot be loaded. The default values are applied.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageLoadingConfigError {
            get {
                return ResourceManager.GetString("MessageLoadingConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vive Pro Eye is not connected. Please check your device or switch the target device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNotProEye {
            get {
                return ResourceManager.GetString("MessageNotProEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new version has been released: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUpdateExists {
            get {
                return ResourceManager.GetString("MessageUpdateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking the update failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUpdateFailed {
            get {
                return ResourceManager.GetString("MessageUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderClip {
            get {
                return ResourceManager.GetString("OSCHeaderClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust Curve に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderCurve {
            get {
                return ResourceManager.GetString("OSCHeaderCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderGain {
            get {
                return ResourceManager.GetString("OSCHeaderGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSC Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderKey {
            get {
                return ResourceManager.GetString("OSCHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderRange {
            get {
                return ResourceManager.GetString("OSCHeaderRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Val に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderValue {
            get {
                return ResourceManager.GetString("OSCHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterAll {
            get {
                return ResourceManager.GetString("OSCSignalFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Essential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterEssential {
            get {
                return ResourceManager.GetString("OSCSignalFilterEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye (Computed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterEyeComputed {
            get {
                return ResourceManager.GetString("OSCSignalFilterEyeComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye (Raw) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterEyeRaw {
            get {
                return ResourceManager.GetString("OSCSignalFilterEyeRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gaze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterGaze {
            get {
                return ResourceManager.GetString("OSCSignalFilterGaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lip (Computed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterLipComputed {
            get {
                return ResourceManager.GetString("OSCSignalFilterLipComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lip (Raw) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterLipRaw {
            get {
                return ResourceManager.GetString("OSCSignalFilterLipRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCSignalFilterOnlyEnabled {
            get {
                return ResourceManager.GetString("OSCSignalFilterOnlyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingDisabled {
            get {
                return ResourceManager.GetString("TrackingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingRunning {
            get {
                return ResourceManager.GetString("TrackingRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingStarting {
            get {
                return ResourceManager.GetString("TrackingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingStopping {
            get {
                return ResourceManager.GetString("TrackingStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unavailable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingUnavailable {
            get {
                return ResourceManager.GetString("TrackingUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No value inputted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationNoValue {
            get {
                return ResourceManager.GetString("ValidationNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracking Configurations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowHeaderDeviceConfigs {
            get {
                return ResourceManager.GetString("WindowHeaderDeviceConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Configurations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowHeaderGeneralConfigs {
            get {
                return ResourceManager.GetString("WindowHeaderGeneralConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AkaneFacialOSC: Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleConfig {
            get {
                return ResourceManager.GetString("WindowTitleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AkaneFacialOSC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleMainWindow {
            get {
                return ResourceManager.GetString("WindowTitleMainWindow", resourceCulture);
            }
        }
    }
}
