//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZW.FacialOSC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AZW.FacialOSC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigButtonSave {
            get {
                return ResourceManager.GetString("ConfigButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save (*) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigButtonSaveDirty {
            get {
                return ResourceManager.GetString("ConfigButtonSaveDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye-tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigEyeTracker {
            get {
                return ResourceManager.GetString("ConfigEyeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLanguage {
            get {
                return ResourceManager.GetString("ConfigLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eye-tracking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EyeTrackingButton {
            get {
                return ResourceManager.GetString("EyeTrackingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Facial-Tracking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaceTrackingButton {
            get {
                return ResourceManager.GetString("FaceTrackingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderCenter {
            get {
                return ResourceManager.GetString("OSCHeaderCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderGain {
            get {
                return ResourceManager.GetString("OSCHeaderGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSC Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderKey {
            get {
                return ResourceManager.GetString("OSCHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Val に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSCHeaderValue {
            get {
                return ResourceManager.GetString("OSCHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingDisabled {
            get {
                return ResourceManager.GetString("TrackingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingRunning {
            get {
                return ResourceManager.GetString("TrackingRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingStarting {
            get {
                return ResourceManager.GetString("TrackingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingStopping {
            get {
                return ResourceManager.GetString("TrackingStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unavailable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TrackingUnavailable {
            get {
                return ResourceManager.GetString("TrackingUnavailable", resourceCulture);
            }
        }
    }
}
